## NUMPY

In [2]:
import numpy as np

## Datatypes and attributes 

In [3]:
# numpys main datatype is ndarray (n dimensional array)

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array( [ [1,2,3.0],
                 [4,6.5,7] ])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3. ],
       [4. , 6.5, 7. ]])

## Shapes

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(3, 2, 3)

dimensions

In [10]:
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

datatype

In [11]:
a1.dtype

dtype('int32')

size

In [12]:
a1.size , a2.size , a3.size

(3, 6, 18)

In [13]:
# type of array 

type(a1)

numpy.ndarray

In [14]:
# create a dataframe from numpy array 

In [15]:
import pandas as pd 

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  6.5  7.0

## Creating arrays

In [20]:



sample_array = np.array ([1,2,3])
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int32')

In [22]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# 0 is start  , 10 is end  , 2 is the places skipped 

range_array = np.arange(0,10 ,2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
# random array

random_array = np.random.randint(0 , 10  , size= (3,5) )
random_array

array([[5, 1, 3, 8, 7],
       [8, 7, 1, 3, 0],
       [4, 6, 0, 6, 0]])

In [32]:
# random array 2 

random_array_2 = np.random.random((5,3))
random_array_2

array([[0.90881351, 0.8235962 , 0.0498506 ],
       [0.34635672, 0.88345499, 0.35982659],
       [0.78115484, 0.10675769, 0.25826551],
       [0.87490363, 0.24037705, 0.3222645 ],
       [0.06444533, 0.28832337, 0.47159343]])

In [33]:
# random array 3 

random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.21449482, 0.76432121, 0.58074519],
       [0.89029925, 0.23413518, 0.04954742],
       [0.12776006, 0.12387942, 0.94057739],
       [0.1587051 , 0.04752928, 0.59846971],
       [0.96586837, 0.40558074, 0.72812167]])

## NUMpy random seed

In [35]:
# pseudo_random_arrays

# np.random.seed() : generating random nos that are reproducable 

np.random.seed(seed = 0)  # change seed values for different values 
random_array_4 = np.random.randint(10 , size = (5,3))
random_array_4


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [39]:
np.random.seed(7) ##important 
randomarray_5 = np.random.random((5,3))
randomarray_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

*random nos are pseudo random